trainer:
  _target_: lightning.Trainer
  accelerator: gpu
  max_epochs: 3300
  logger:
    _target_: lightning.pytorch.loggers.WandbLogger
    project: dialogue-separator
  check_val_every_n_epoch: 10
  precision: 16-mixed
  strategy:
    _target_: lightning.pytorch.strategies.DDPStrategy
    static_graph: true
  callbacks:
    - _target_: litmodels.integrations.LightningModelCheckpoint
      model_registry: koacai/speech/dialogue-separator
  fast_dev_run: false
