trainer:
  _target_: lightning.Trainer
  accelerator: gpu
  max_epochs: 3300
  logger:
    _target_: lightning.pytorch.loggers.WandbLogger
    project: geneses
  check_val_every_n_epoch: 1
  precision: 16-mixed
  strategy:
    _target_: lightning.pytorch.strategies.DDPStrategy
    static_graph: true
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  callbacks:
    - _target_: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      monitor: validation_loss
      mode: min
      patience: 30
      verbose: true
      min_delta: 0.001
  fast_dev_run: false
